const posts = [
  {
    id: 1,
    image: "https://via.placeholder.com/150",
    title: "Exploring the Mountains",
    text: "Just came back from an amazing trip to the Rockies! The view from the top was breathtaking.",
    date: "2024-09-22",
    author: "Alice",
    likes: 35,
    shares: 12,
    comments: [
      "Wow, that must have been incredible!",
      "Next time, take me with you!",
    ],
  },
  {
    id: 2,
    image: "https://via.placeholder.com/150",
    title: "My New Art Project",
    text: "Finally completed my abstract painting series. Art is such a deep form of expression.",
    date: "2024-09-21",
    author: "John",
    likes: 28,
    shares: 6,
    comments: [
      "Love this! So inspiring!",
      "These colors are amazing, great job!",
    ],
  },
  {
    id: 3,
    image: "https://via.placeholder.com/150",
    title: "Tech Conference 2024 Highlights",
    text: "Attended the Tech Conference and learned so much about AI and machine learning. Can't wait to apply these ideas!",
    date: "2024-09-20",
    author: "Lisa",
    likes: 42,
    shares: 18,
    comments: [
      "I wish I could've attended!",
      "So jealous, sounds like a great experience!",
    ],
  },
  {
    id: 4,
    image: "https://via.placeholder.com/150",
    title: "Homemade Pizza Night",
    text: "Tried a new pizza recipe at home tonight. The dough came out perfect, and the toppings were fresh from the garden.",
    date: "2024-09-19",
    author: "Tom",
    likes: 50,
    shares: 9,
    comments: ["That looks delicious!", "Please share the recipe!"],
  },
  {
    id: 5,
    image: "https://via.placeholder.com/150",
    title: "Evening Run in the Park",
    text: "Had a great 5K run at the park today. The weather was perfect, and I beat my personal record!",
    date: "2024-09-18",
    author: "Emma",
    likes: 64,
    shares: 14,
    comments: [
      "Congrats on the new PR!",
      "Keep pushing! You’re doing amazing!",
    ],
  },
  {
    id: 6,
    image: "https://via.placeholder.com/150",
    title: "Book Review: 'Atomic Habits'",
    text: "Finished reading 'Atomic Habits'. This book has changed my outlook on building lasting habits. Highly recommend!",
    date: "2024-09-17",
    author: "Sophia",
    likes: 48,
    shares: 21,
    comments: [
      "This is on my reading list!",
      "I loved that book too, so impactful!",
    ],
  },
  {
    id: 7,
    image: "https://via.placeholder.com/150",
    title: "Family BBQ",
    text: "Had an amazing BBQ with the family today. Great food, great company. Nothing beats spending time with loved ones.",
    date: "2024-09-16",
    author: "Michael",
    likes: 75,
    shares: 10,
    comments: ["Family time is the best!", "That BBQ looks fantastic!"],
  },
  {
    id: 8,
    image: "https://via.placeholder.com/150",
    title: "Yoga for Beginners",
    text: "Started my yoga journey today. It’s harder than it looks, but I’m loving the challenge!",
    date: "2024-09-15",
    author: "Sara",
    likes: 40,
    shares: 8,
    comments: [
      "Yoga is amazing! Keep at it!",
      "I’ve been meaning to try this too!",
    ],
  },
  {
    id: 9,
    image: "https://via.placeholder.com/150",
    title: "DIY Home Renovation",
    text: "Spent the weekend working on our DIY home renovation project. The living room is finally coming together!",
    date: "2024-09-14",
    author: "David",
    likes: 58,
    shares: 11,
    comments: ["Impressive work!", "Can’t wait to see the final result!"],
  },
  {
    id: 10,
    image: "https://via.placeholder.com/150",
    title: "Weekend Getaway to the Beach",
    text: "Took a spontaneous trip to the beach this weekend. The ocean waves and sunset were so calming.",
    date: "2024-09-13",
    author: "Laura",
    likes: 82,
    shares: 25,
    comments: [
      "That sounds like a perfect weekend!",
      "I need a beach getaway too!",
    ],
  },
];

export default posts;
